### ISSUE TITLE
doesn't run on pnpm

### ISSUE THREAD

**Issue by adeyahya** [adeyahya/prisma-typebox-generator#10]
```
Error: Generator at prisma-typebox-generator could not start:

/bin/sh: prisma-typebox-generator: command not found

 ERROR  Command failed with exit code 1: /Users/adeyahya/Library/pnpm/store/v3/tmp/dlx-89483/node_modules/.bin/prisma generate

pnpm: Command failed with exit code 1: /Users/adeyahya/Library/pnpm/store/v3/tmp/dlx-89483/node_modules/.bin/prisma generate
    at makeError (/Users/adeyahya/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpx.cjs:16527:17)
    at handlePromise (/Users/adeyahya/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpx.cjs:17098:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.handler [as dlx] (/Users/adeyahya/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpx.cjs:183480:7)
    at async /Users/adeyahya/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpx.cjs:192579:21
    at async run (/Users/adeyahya/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpx.cjs:192553:34)
    at async /Users/adeyahya/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpx.cjs:192625:5
```

**Comment by joshmossas** [comment]
Ran into this issue. I was able to get it working by running
```
pnpm prisma generate
```

Instead of
```
prisma generate
```

**Comment by adeyahya** [comment]
Since I can't dedicate time to maintain this repository, I've updated the readme to refer to [prismabox](https://github.com/m1212e/prismabox) instead. This is because it offers better support, maintained, and has a more suitable name.
